name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - alabaster=0.7.12=pyhd3eb1b0_0
  - alsa-lib=1.2.3=h516909a_0
  - babel=2.9.1=pyhd3eb1b0_0
  - blas=1.0=mkl
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.17.1=h7f98852_1
  - ca-certificates=2021.7.5=h06a4308_1
  - cairo=1.16.0=hf32fb01_1
  - certifi=2021.5.30=py38h06a4308_0
  - cffi=1.14.6=py38h400218f_0
  - chardet=4.0.0=py38h06a4308_1003
  - cryptography=3.4.7=py38hd23ed53_0
  - dbus=1.13.18=hb2f20db_0
  - expat=2.4.1=h2531618_2
  - fontconfig=2.13.1=h6c09931_0
  - freetype=2.10.4=h5ab3b9f_0
  - gettext=0.19.8.1=h0b5b191_1005
  - gitdb=4.0.7=pyhd3eb1b0_0
  - gitpython=3.1.18=pyhd3eb1b0_1
  - glib=2.68.3=h9c3ff4c_0
  - glib-tools=2.68.3=h9c3ff4c_0
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - graphite2=1.3.13=h58526e2_1001
  - gst-plugins-base=1.18.4=hf529b03_2
  - gstreamer=1.18.4=h76c114f_2
  - harfbuzz=2.8.2=h83ec7ef_0
  - hdf5=1.10.6=nompi_h7c3c948_1111
  - icu=68.1=h58526e2_0
  - idna=2.10=pyhd3eb1b0_0
  - imagesize=1.2.0=pyhd3eb1b0_0
  - intel-openmp=2021.2.0=h06a4308_610
  - jasper=1.900.1=h07fcdf6_1006
  - jinja2=3.0.1=pyhd3eb1b0_0
  - jpeg=9d=h36c2ea0_0
  - krb5=1.19.1=hcc1bbae_0
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libblas=3.9.0=9_mkl
  - libcblas=3.9.0=9_mkl
  - libclang=11.1.0=default_ha53f305_1
  - libcurl=7.77.0=h2574ce0_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=hcdb4288_3
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libglib=2.68.3=h3e27bee_0
  - libgomp=9.3.0=h5101ec6_17
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=9_mkl
  - liblapacke=3.9.0=9_mkl
  - libllvm11=11.1.0=hf817b99_2
  - libnghttp2=1.43.0=h812cca2_0
  - libogg=1.3.4=h7f98852_1
  - libopencv=4.5.2=py38hcdf9bf1_0
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.37=hbc83047_0
  - libpq=13.3=hd57d9b9_0
  - libprotobuf=3.15.8=h780b84a_0
  - libssh2=1.9.0=ha56f1ee_6
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtiff=4.2.0=h85742a9_0
  - libuuid=1.0.3=h1bed415_2
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp-base=1.2.0=h27cfd23_0
  - libxcb=1.14=h7b6447c_0
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.12=h72842e0_0
  - lz4-c=1.9.3=h2531618_0
  - markupsafe=2.0.1=py38h27cfd23_0
  - mkl=2021.2.0=h06a4308_296
  - mkl-service=2.3.0=py38h27cfd23_1
  - mkl_fft=1.3.0=py38h42c9631_2
  - mkl_random=1.2.1=py38ha9443f7_2
  - mysql-common=8.0.25=ha770c72_0
  - mysql-libs=8.0.25=h935591d_0
  - ncurses=6.2=he6710b0_1
  - nettle=3.6=he412f7d_0
  - nspr=4.30=h9c3ff4c_0
  - nss=3.67=hb5efdd6_0
  - numpy=1.20.2=py38h2d18471_0
  - numpy-base=1.20.2=py38hfae3a4d_0
  - olefile=0.46=py_0
  - opencv=4.5.2=py38h578d9bd_0
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.3.0=h05c96fa_1
  - openssl=1.1.1k=h27cfd23_0
  - packaging=21.0=pyhd3eb1b0_0
  - pcre=8.45=h295c915_0
  - pillow=8.3.1=py38h2c7a002_0
  - pip=21.1.3=py38h06a4308_0
  - pixman=0.40.0=h36c2ea0_0
  - py-opencv=4.5.2=py38hd0cf306_0
  - pycparser=2.20=py_2
  - pygments=2.9.0=pyhd3eb1b0_0
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.12.3=py38h578d9bd_7
  - pyqt-impl=5.12.3=py38h7400c14_7
  - pyqt5-sip=4.19.18=py38h709712a_7
  - pyqtchart=5.12=py38h7400c14_7
  - pyqtwebengine=5.12.1=py38h7400c14_7
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.10=h12debd9_8
  - python_abi=3.8=2_cp38
  - pytz=2021.1=pyhd3eb1b0_0
  - pyyaml=5.4.1=py38h27cfd23_1
  - qt=5.12.9=hda022c4_4
  - readline=8.1=h27cfd23_0
  - requests=2.25.1=pyhd3eb1b0_0
  - scipy=1.6.2=py38had2a1c9_1
  - setuptools=52.0.0=py38h06a4308_0
  - sip=4.19.13=py38he6710b0_0
  - six=1.16.0=pyhd3eb1b0_0
  - smmap=4.0.0=pyhd3eb1b0_0
  - snowballstemmer=2.1.0=pyhd3eb1b0_0
  - sphinx=4.0.2=pyhd3eb1b0_0
  - sphinxcontrib-applehelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-devhelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd3eb1b0_0
  - sqlite=3.36.0=hc218d9a_0
  - tk=8.6.10=hbc83047_0
  - typing-extensions=3.10.0.0=hd3eb1b0_0
  - typing_extensions=3.10.0.0=pyh06a4308_0
  - urllib3=1.26.6=pyhd3eb1b0_1
  - wheel=0.36.2=pyhd3eb1b0_0
  - x264=1!161.3030=h7f98852_1
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - altgraph==0.17
    - click==8.0.1
    - coloredlogs==15.0.1
    - cycler==0.10.0
    - docutils==0.16
    - evdev==1.4.0
    - ghp-import==2.0.1
    - humanfriendly==9.2
    - importlib-metadata==4.6.1
    - kiwisolver==1.3.1
    - markdown==3.3.4
    - matplotlib==3.4.2
    - mergedeep==1.3.4
    - mkdocs==1.2.1
    - pgi==0.0.11.2
    - playsound==1.3.0
    - pyinstaller==4.3
    - pyinstaller-hooks-contrib==2021.2
    - pynput==1.7.3
    - python-dateutil==2.8.1
    - python-mpv==0.5.2
    - python-xlib==0.31
    - pyyaml-env-tag==0.1
    - screeninfo==0.6.7
    - sphinx-rtd-theme==0.5.2
    - watchdog==2.1.3
    - zipp==3.5.0
prefix: /home/ubuntu/miniconda3
