name: build-installer
channels:
  - defaults
dependencies:
  - altgraph=0.17=pyhd3eb1b0_0
  - beautifulsoup4=4.10.0=pyh06a4308_0
  - brotlipy=0.7.0=py39h2bbff1b_1003
  - ca-certificates=2021.9.30=haa95532_1
  - certifi=2021.10.8=py39haa95532_0
  - cffi=1.14.6=py39h2bbff1b_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=3.4.8=py39h71e12ea_0
  - future=0.18.2=py39haa95532_1
  - idna=3.2=pyhd3eb1b0_0
  - macholib=1.14=pyhd3eb1b0_1
  - openssl=1.1.1l=h2bbff1b_0
  - packaging=21.0=pyhd3eb1b0_0
  - pefile=2019.4.18=py_0
  - pip=21.2.4=py39haa95532_0
  - pycparser=2.20=py_2
  - pycryptodome=3.10.1=py39h2bbff1b_0
  - pyinstaller=3.6=py39h8cc25b3_6
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pysocks=1.7.1=py39haa95532_0
  - python=3.9.7=h6244533_1
  - pywin32=228=py39hbaba5e8_1
  - pywin32-ctypes=0.2.0=py39haa95532_1000
  - requests=2.26.0=pyhd3eb1b0_0
  - setuptools=58.0.4=py39haa95532_0
  - six=1.16.0=pyhd3eb1b0_0
  - soupsieve=2.2.1=pyhd3eb1b0_0
  - sqlite=3.36.0=h2bbff1b_0
  - tqdm=4.62.2=pyhd3eb1b0_1
  - tzdata=2021a=h5d7bf9c_0
  - urllib3=1.26.7=pyhd3eb1b0_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.37.0=pyhd3eb1b0_1
  - win_inet_pton=1.1.0=py39haa95532_0
  - wincertstore=0.2=py39haa95532_2
prefix: C:\Users\win10\miniconda3\envs\build-installer
