# video projection parameters
# Do not change any parameters here unless you know exactly what you are doing!
# For VR video filer options see: https://ffmpeg.org/ffmpeg-filters.html#v360

vr_he_180_sbs:
  name: '3D VR Video 180'
  video_filter: 'v360=input=he:in_stereo=sbs:pitch=${pitch}:yaw=${yaw}:roll=${roll}:output=flat:d_fov=${fov}:w=${width}:h=${height}'
  parameter:
    height: 720
    width: 1240
    fov: 100
    pitch: -45
    yaw: 0
    roll: 0
  keys:
    pitch:
      increase: "w"
      decrease: "s"
    yaw:
      increase: "d"
      decrease: "a"
    roll:
      increase: "e"
      decrease: "q"
    fov:
      increase: "-"
      decrease: "+"

vr_fisheye_200_sbs:
  name: '3D VR Video Fisheye 200'
  video_filter: 'v360=input=fisheye:in_stereo=sbs:id_fov=200:pitch=${pitch}:yaw=${yaw}:roll=${roll}:output=flat:d_fov=${fov}:w=${width}:h=${height}'
  parameter:
    height: 720
    width: 1240
    fov: 100
    pitch: -45
    yaw: 0
    roll: 0
  keys:
    pitch:
      increase: "w"
      decrease: "s"
    yaw:
      increase: "d"
      decrease: "a"
    roll:
      increase: "e"
      decrease: "q"
    fov:
      increase: "-"
      decrease: "+"

vr_equirect_360_ou:
  name: 'Vertical 3D VR Video 360/180'
  video_filter: 'v360=input=equirect:in_stereo=tb:pitch=${pitch}:yaw=${yaw}:roll=${roll}:output=flat:d_fov=${fov}:w=${width}:h=${height}'
  parameter:
    height: 720
    width: 1240
    fov: 100
    pitch: -45
    yaw: 0
    roll: 0
  keys:
    pitch:
      increase: "w"
      decrease: "s"
    yaw:
      increase: "d"
      decrease: "a"
    roll:
      increase: "e"
      decrease: "q"
    fov:
      increase: "-"
      decrease: "+"

vr_he_180_ou:
  name: 'Vertical 3D VR Video 180'
  video_filter: 'v360=input=he:in_stereo=tb:pitch=${pitch}:yaw=${yaw}:roll=${roll}:output=flat:d_fov=${fov}:w=${width}:h=${height}'
  parameter:
    height: 720
    width: 1240
    fov: 100
    pitch: -45
    yaw: 0
    roll: 0
  keys:
    pitch:
      increase: "w"
      decrease: "s"
    yaw:
      increase: "d"
      decrease: "a"
    roll:
      increase: "e"
      decrease: "q"
    fov:
      increase: "-"
      decrease: "+"

flat:
  name: '2D Video'
  video_filter: 'scale=${width}:${height}'
  parameter:
    height: 720
    width: -1
